In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 999)
pd.set_option('display.width', 500)
pd.set_option('display.notebook_repr_html', True)
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import math
from collections import defaultdict
from collections import Counter
from astropy.io import fits

import importlib
import ctypes

In [2]:
import ephem_forces
import demo
import demo_why

[0. 0. 0. 0. 0. 0.]


In [ ]:
demo.states[0,:,:].shape, demo.instates.shape

In [ ]:
demo.times, demo.states, demo.n_particles, demo.n_out

In [3]:
1e-3*24*60

1.44

In [5]:
a = np.array([[2, -3, 4], [3, 4, -5], [4, -5, 6]])

In [6]:
a

array([[ 2, -3,  4],
       [ 3,  4, -5],
       [ 4, -5,  6]])

In [7]:
b = np.array([8, -4, 12])

In [8]:
np.linalg.solve(a, b)

array([1., 2., 3.])

In [9]:
a = np.array([[1, -1, -1], [2, 3, 2], [4, 3, -2]])

In [10]:
b = np.array([1, 8, -2])

In [11]:
np.linalg.solve(a, b)

array([ 3., -2.,  4.])

In [12]:
a = np.array([[4, 6, -3], [3, 4, -6], [6, -3, 4]])

In [13]:
b = np.array([24, 2, 46])

In [14]:
np.linalg.solve(a, b)

array([6., 2., 4.])